### ISSUE TITLE
Start building the wings already!

### ISSUE THREAD

**Issue by danielschonfeld** [palamedes/palamedes.github.com#1]
Both my wife and I are glued to your videos, having recently heard and taking a liking to the idea of building an RV-10 of our own one day.

So.... get over the hangover, and get to work! Your videos are absolutely awesome! :+1:

**Comment by palamedes** [comment]
@danielschonfeld Awesome!  The RV10 is a thing of magic and if I can build one.. ANYONE can hah

No hangover here.. the beer I have been drinking of late is flavorful but not very strong =/   Good I guess.

Wings are here next week!!!!

**Comment by danielschonfeld** [comment]
@palamedes lol and that's probably a good thing, tho happy new year!

Thanks for taking the time and going through the trouble of making the videos, they're really awesome. 

Can't wait till the wings are here :smile: we'll sit and count down the minutes with you..

**Comment by palamedes** [comment]
Sure!  I'm enjoying it so the videos are actually no problem.. just.. extra work.. 

Out of curiosity do I have a link to mygithub issues page somewhere or are you just smart enough to know to use it? =)

**Comment by danielschonfeld** [comment]
@palamedes on the bottom of your RSOW.com blog there's a link to your github *profile* page. I figured this is the most appropriate repo to open the "issue" on :wink: 

As far as using github, wish I could take the credit but i'm a fellow software engineer/devops guy so github is no foreign land to me.  (My day job is airline pilot so that should explain the fascination with the RV-10)

**Comment by danielschonfeld** [comment]
@palamedes out of curiosity - how much is the T-hangar rental per month in your local airport?

**Comment by palamedes** [comment]
OH wow I completely forgot about that link.. Been awhile since I did that skin =)

Which airline do you work for?  How long have you done that?  That's a bit of a step away from software =)  

And hangars run from $200 to 300 here..

**Comment by danielschonfeld** [comment]
Work for a Cargo company called Southern Air, been in the airlines for 10 years so far.  I'm also part of SocialRank doing DevOps.  One of these days I'll decide what I should do for a career and what for hobby in the long term.... or so I keep telling myself :wink: 

Thank you for the info! Maybe one of these days I could turn this into a reality... Until then I'll keep watching your videos intently :smile:

**Comment by danielschonfeld** [comment]
And no you can't close this issue until work on the wings has started! :lollipop:

**Comment by palamedes** [comment]
Ha fair enough.

**Comment by palamedes** [comment]
Hint.

**Comment by danielschonfeld** [comment]
No waaaaaaayyyyyyy! Happy new year Jason! :)

**Comment by palamedes** [comment]
Thanks brother.. I'll have videos of the boring delivery and inventory soon =0

**Comment by danielschonfeld** [comment]
Excited right there with you, awesome video as always! wife and I are like netflix binge watching your build log :wink:
